name: Radicale
description: A free and open-source CalDAV and CardDAV server
version: 3.1.8r1
slug: radicale
webui: https://[HOST]:[PORT:5232]
map:
- ssl:ro
- addon_config:rw
init: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
ports:
  5232/tcp: '5232'
image: ghcr.io/marcuswagberg/hass-radicale-{arch}
options:
  ssl: true
  certfile: radicale.cert
  keyfile: radicale.key
  language: en_US
  timezone: Europe/London
  users:
  - username: hass
    password: changeme
schema:
  ssl: bool
  certfile: str
  keyfile: str
  language: match(^[A-Za-z0-9_]*$)
  timezone: match(^[A-Za-z0-9/]*$)
  users:
  - username: match(^[A-Za-z0-9_]*$)
    password: password
