name: Intermedium
description: A smtp to homeassistant notify proxy
version: 1.0.0
slug: intermedium
init: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
ports:
  8025/tcp: '8025'
homeassistant_api: true
image: ghcr.io/marcuswagberg/hass-intermedium-{arch}
options:
  users:
  - email: intermedium@hass.local
    notify_service: notify
schema:
  users:
  - email: email
    notify_service: match(^[A-Za-z0-9_]*$)
